language: ruby
bundler_args: --without development production
sudo: false
rvm:
- 2.3.1
script:
- RAILS_ENV=test COVERAGE=true bundle exec rake db:setup spec
env:
- telegram_token=xxx medlink_token=xxx medlink_url=xxx
branches:
  only:
  - master
notifications:
  email:
    recipients:
    - jamesdabbs@gmail.com
    on_success: change
    on_failure: always
addons:
  postgresql: "9.4"
